#
# https://docs.ansible.com/ansible/latest/collections/amazon/aws/aws_ec2_inventory.html
#

plugin: amazon.aws.aws_ec2
regions:
  - us-west-2
filters:
  instance-state-name: running
  tag:env:
    - ansible

hostnames:
  - tag:Name
  - ip-address

keyed_groups:
  - key: tags.env
    prefix: tag

groups:
  ansible: "'ansible' in tags.env"  
  ansible1: tags.get('env') == 'ansible'

compose:
  ansible_host: public_ip_address 
  #ansible_host: private_ip_address
  #ansible_host: public_dns_name
  


