---

- name: "Playbook to review tasks"
  hosts: all
  become: true
  tasks:
    - name: "Install nginx"
      ansible.builtin.apt:
        name: nginx
        state: latest

    - name: "Command module"
      ansible.builtin.command: '/usr/bin/systemctl status nginx'
      ignore_errors: true
      notify: Restart nginx

    - name: "Restart all"
      ansible.builtin.command: 'echo "This is the task to restart all services"'
      notify: "restart all web services"

  handlers:
    - name: "Restart nginx"
      ansible.builtin.service:
        name: nginx
        state: restarted
      listen: "restart all web services"

    - name: "Restart memcached"
      ansible.builtin.service:
        name: memcached
        state: restarted
      listen: "restart all web services"
      check_mode: yes
