---
- name: Install Prometheus Node Exporter
  hosts: prometheus_clients
  become: yes

  vars:
    node_exporter_version: "1.8.2"
    node_exporter_user: "node_exporter"
    node_exporter_group: "node_exporter"
    node_exporter_install_dir: "/usr/local/bin"
    node_exporter_download_dir: "/opt/downloads"

  tasks:
    - name: Create Directories
      ansible.builtin.file:
        path: "{{ node_exporter_download_dir }}"
        state: directory
        mode: '0755'

    - name: Create Node Exporter group
      ansible.builtin.group:
        name: "{{ node_exporter_group }}"

    - name: Create Node Exporter user
      ansible.builtin.user:
        name: "{{ node_exporter_user }}"
        group: "{{ node_exporter_group }}"
        shell: "/sbin/nologin"
        comment: "Node Exporter User"

    - name: Download Node Exporter binary
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: "{{ node_exporter_download_dir }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"

    - name: Extract Node Exporter binary
      ansible.builtin.unarchive:
        remote_src: yes
        src: "{{ node_exporter_download_dir }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: "{{ node_exporter_download_dir }}/"

    - name: Copy Node Exporter binary
      ansible.builtin.copy:
        remote_src: yes
        src: "{{ node_exporter_download_dir }}/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
        dest: "{{ node_exporter_install_dir }}/node_exporter"
        mode: '0755'

    - name: Create Node Exporter systemd service file
      ansible.builtin.template:
        src: "./node_exporter.service.j2"
        dest: "/etc/systemd/system/node_exporter.service"
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start Node Exporter service
      ansible.builtin.systemd:
        name: node_exporter
        enabled: yes
        state: started






















