---
- name: Kubernetes playbook
  hosts: kubernetes
  gather_facts: yes
  become: yes

  vars:
    k8s_name: Anton

  tasks:
    - name: Update and upgrade system packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Initial commands
      shell: "apt-get update && apt-get upgrade -y"

    - name: Install required packages
      apt:
        name:
          - vim
          - curl
          - apt-transport-https
          - git
          - wget
        state: present

    - name: Disable swap
      command: swapoff -a

    - name: Load necessary kernel modules
      shell: |
        modprobe overlay
        modprobe br_netfilter

    - name: Configure sysctl for Kubernetes networking
      copy:
        dest: /etc/sysctl.d/kubernetes.conf
        content: |
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1

    - name: Apply sysctl settings
      command: sysctl --system

    - name: Add Docker GPG key
      shell: |
        mkdir -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

    - name: Add Docker repository
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list

    - name: Install containerd
      apt:
        update_cache: yes
        name: containerd.io
        state: present

    - name: Configure containerd
      shell: |
        containerd config default | tee /etc/containerd/config.toml
        sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
        systemctl restart containerd

    - name: Add Kubernetes GPG key
      shell: |
        mkdir -p -m 755 /etc/apt/keyrings
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes repository
      shell: |
        echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /" | tee /etc/apt/sources.list.d/kubernetes.list

    - name: Install Kubernetes components
      apt:
        update_cache: yes
        name:
          - kubeadm=1.30.1-1.1
          - kubelet=1.30.1-1.1
          - kubectl=1.30.1-1.1
        state: present

    - name: Hold Kubernetes packages
      command: apt-mark hold kubelet kubeadm kubectl

    - name: Display host IP information
      shell: |
        hostname -i
        ip addr show
      register: ip_info

    - debug:
        msg: "Host IP details: {{ ip_info.stdout }}"

    - name: Generate kubeadm configuration file
      copy:
        dest: kubeadm-config.yaml
        content: |
          apiVersion: kubeadm.k8s.io/v1beta3
          kind: ClusterConfiguration
          kubernetesVersion: "1.30.1"
          controlPlaneEndpoint: "k8scp:6443"
          networking:
            podSubnet: 10.1.0.0/16
      tags:
        - init_kubernetes

    - name: Initialize Kubernetes cluster
      command: #kubeadm init --config=kubeadm-config.yaml --upload-certs --node-name=cp
      register: kubeadm_output
      tags:
        - init_kubernetes

    - debug:
        msg: "Kubeadm init output: {{ kubeadm_output.stdout }}"
      tags:
        - init_kubernetes




